### PR TITLE
implement copy/paste for wasm

### LINKED ISSUE #1: Implement Copy and Paste Functionality for wasm target
Wasm can be done using https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html with async API, ideally may be upstreamed to `arboard`.

### PR DESCRIPTION
**Pull request by bytemunch**
closes #1 

my machine has never been able to write to clipboard from native (raw X11 no clipboard manager), that functionality shouldn't have changed but might be worth a test before merge

copy/cut/paste tested working on Chrome Linux X11

### CODE REVIEW

**Comment by Dimchikkk** [comment]
Nice stuff 👍 it's better on Mac now... when `cmd + v` is pressed multiple times to insert multiple times it breaks to insert...but anyway it's much better than without clipboard at all 🎉

**Comment by bytemunch** [comment]
Can't recreate the paste breaking on multiple presses, was using a spoofed UA string for mac inputs, might be OS specific. I'll have a closer look tomorrow

**Comment by bytemunch** [comment]
Oh I've noticed paste happens at key-repeat too, will delegate that work to #63

**Comment by Dimchikkk** [comment]
Yeah, it's buggy on macos, but works perfectly on page refresh, on first copy-paste operation, let's merge it :)

**Pull request merged**
