### PR TITLE
bevy::picking integration and refactoring

### PR DESCRIPTION
**Pull request by ActuallyHappening**
I'm currently working on removing the manual layout stuff like XOffset and the padding in CosmicTextAlign as this is supported natively (per line) in `cosmic_text` already. Extra padding can be done at the UI/Sprite level if desired, currently it is 'cluttering up' the render code.
I'm also slowly working towards 3D support

### CODE REVIEW

**Comment by Dimchikkk** [comment]
Nice!

> I'm also slowly working towards 3D support

Would be cool to update README.md to tell users that 3D support is available once it's implemented.

**Comment by ActuallyHappening** [comment]
Sure, updating the README is the least of my troubles!
I've completely removed a lot of code, including `XOffset` `CosmicPadding` and the `widget` module entirely, as the complexity versus performance was just not worth it. These are breaking changes btw, but greatly simplify the internals and provide a more consistent and configurable API for text alignment

**Comment by ActuallyHappening** [comment]
Also, the seperation of code into modules is quite bugging me, either the whole project knows about every implementation detail of Sprite/UI or only one module does. I think only one module knowing is the correct way to go

**Comment by Dimchikkk** [comment]
> Sure, updating the README is the least of my troubles! I've completely removed a lot of code, including `XOffset` `CosmicPadding` and the `widget` module entirely, as the complexity versus performance was just not worth it. These are breaking changes btw, but greatly simplify the internals and provide a more consistent and configurable API for text alignment

sounds good, I love simplicity.

**Comment by Dimchikkk** [comment]
> Also, the seperation of code into modules is quite bugging me, either the whole project knows about every implementation detail of Sprite/UI or only one module does. I think only one module knowing is the correct way to go

Yeah, ECS pattern / modules separation have own pros & cons.

**Comment by ActuallyHappening** [comment]
The main picking interactions are implemented, only a few minor changes for state changes and then all primary interactions use `bevy::picking`
Tasks after this:
- Update util functions to use bevy::picking. This will probably mean moving them from systems to a addable plugin
- Remove the old `get_node_cursor_pos` and depending code
- Move to using the `plugin_group!` macro and make public relevant plugins that should be disableable
- Make a trait `RenderTarget` that encapsulates the primary information needed for each implementation

3D support will come after these changes are made, as it will be significantly easier then

**Comment by ActuallyHappening** [comment]
OK, these changes fully support `bevy::picking` now, ready to review + merge
I've ignored the runtime test for now because I've tried to test bevy before when upgrading from 0.13 -> 0.14 or (something like that) and it was a pain, I've manually tested the examples and the ones I tested worked perfectly

**Comment by ActuallyHappening** [comment]
Actually, the basic_ui example is broken, will fix later

**Comment by ActuallyHappening** [comment]
Ok now clicking is broken after extensive editting, because of reading the buffer size from CosmicEditBuffer even if rendering is done using CosmicEditor, will fix

**Comment by Dimchikkk** [comment]
lovely changes, are you testing wasm as well?

**Comment by ActuallyHappening** [comment]
> lovely changes, are you testing wasm as well?

I know how but for the moment I'm not, before I mark as ready for review I'll run through all the examples and wasm as well

**Comment by ActuallyHappening** [comment]
Unfortunately, scrolling is all but broken and I can't work out why/how
I've run through all examples and they work, plus wasm works
So far I've:
- refactored all render-target specific code into one module: render_implementations
- refactors all input code into one module and public submodules: input
- extracted important types into seperate modules, e.g. crate::buffer, crate::editor, crate::password, crate::placeholder etc

I'm still a little annoyed at the state of scrolling support in `cosmic_text` itself, but nothing much I can do from my end as a crates-io consumer
I'll add 3D support (finally!) in a different PR

**Comment by ActuallyHappening** [comment]
This is a very breaking change btw, the exposed API to focus now uses observers so you have to .observe(focus_on_click) instead of using that old util func

**Comment by Dimchikkk** [comment]
> Unfortunately, scrolling is all but broken and I can't work out why/how

so this is regression bug? if yes, could you create issue that describes the issue before I approve this pr.

**Comment by ActuallyHappening** [comment]
No its not a regression from this repos main f3b2500b80178ff233e39b9408b7dedcae101571
I can open an issue on this repo, though I've already opened an issue on the cosmic-text repo: https://github.com/pop-os/cosmic-text/issues/335
Its also not a regression from the bevy 0.14 version of this library e8a853a
I don't know how to fix it, I just noticed it for the first time in this PR because I added an example `scroll.rs` to test the behaviour and noticed it was broken

**Comment by Dimchikkk** [comment]
Hm. I've run basic_ui from main and basic scroll functionality works fine to me.

**Review by Dimchikkk — APPROVED** [review]

**Comment by ActuallyHappening** [comment]
Huh, interesting, this isn't that important to me atm so I'll leave it for now

**Comment by Dimchikkk** [comment]
@ActuallyHappening is this PR ready to be merged from your perspective?

**Comment by Dimchikkk** [comment]
> I'll add 3D support (finally!) in a different PR

If you can add nice example with 3d would be cool

In the past I had idea to have a cube and user can type on different sides of the cube, just my fantasies 😄

**Comment by ActuallyHappening** [comment]
Yeah its ready to be merged
I have a branch 3d-support on my fork that I'm working on 3D support for, its has an example `basic_3d`, but I'll open a seperate PR so that this picking support can be merged first :)
The example uses a plane, because for simplicity I'm only implementing support for planes/rectangles with no Z component so that the texture renders onto only one face

**Pull request merged**
