### PR TITLE
add editor restrictions + example

### LINKED ISSUE #22: Provide max character / max line limits
Will make #17 simpler as single line inputs will be a common use-case, and adds ways for such limits to extend to other use cases (e.g. username length limits)

### PR DESCRIPTION
**Pull request by bytemunch**
set_text does not respect these limits, unsure of best way to implement them in that function. Think it's object oriented brain biting me here, need to reframe the issue

Will close #22 and #17

### CODE REVIEW

**Comment by Dimchikkk** [comment]
API looks nice though 👍

**Comment by Dimchikkk** [comment]
> unsure of best way to implement them in that function

just "validate" input before giving it to cosmic-text? cut to limits if invalid?

**Comment by Dimchikkk** [comment]
image
If you can add little border would be amazing :)

**Review by Dimchikkk — APPROVED** [review]

**Comment by bytemunch** [comment]
yea looks better with border :)

**Comment by Dimchikkk** [comment]
@bytemunch plugin looks better now after your improvements, thanks for contribution :)

**Pull request merged**
