### PR TITLE
Bevy 0.12

### LINKED ISSUE #117: Bevy 0.12 support
As the title suggests, `bevy_cosmic_edit` doesn't have support for bevy 0.12 yet.

### PR DESCRIPTION
**Pull request by bytemunch**
closes #117 

Bumps own version
Bumps bevy version
Bumps cosmic-text version (cos why not throw that in too lol, doesn't seem to be any breaking changes)

### CODE REVIEW

**Comment by Dimchikkk** [comment]
Main:
image

Current branch:
image

Text scaling looks broken on Retina.

**Comment by bytemunch** [comment]
> bump lock

aaaaah no my noob is showing :')

> Text scaling looks broken on Retina.

Gah I really need to get used to testing on HiDPI displays, my laptop *has* one. Investigating 🧐

**Comment by Dimchikkk** [comment]
also bumped `wasm-bindgen = "0.2.88"`, so you have to run `cargo install wasm-server-runner --force` if previous version is installed.

**Comment by Dimchikkk** [comment]
> Gah I really need to get used to testing on HiDPI displays, my laptop has one. Investigating 🧐

It's interesting that if I move app from Mac Display to HP monitor and back - scaling is fine. So seems like only "initial" scaling is wrong.

**Comment by Dimchikkk** [comment]
Hm, backspace doesn't work for me at all on this branch (tested on desktop target).

**Comment by bytemunch** [comment]
oh my life keeps getting in the way at the moment

yeah backspace was broken, seems like the editor action only being needed on wasm is gone now. so pushed for time today i only tested if it rendered, typed, ctrl-a'd and deleted my bad

doing wasm update and tests now hopefully will get something up and running soon

**Comment by Dimchikkk** [comment]
@bytemunch no hurry, life first <3

**Comment by bytemunch** [comment]
@StaffEngineer would appreciate a test, my screens only differ by 0.8 in scale factor and it's hard to tell by eye :)

**Comment by Dimchikkk** [comment]
1. Backspace started to work but the bug that it works also for readonly widgets is back.
2. Bug with scaling for Mac Display is still there:

Before moving to non-mac display:
image
After moving to non-mac display and back:
image

**Comment by bytemunch** [comment]
Backspace bug fix just isn't merged in this branch. I'm kinda lost with the Retina things then, has the scale factor that a retina display gets changed between this branch and main?

**Comment by Dimchikkk** [comment]
main was fine, let me try to log scale value and get back to you :)

**Comment by Dimchikkk** [comment]
@bytemunch wow, bevy's bug or even winit 😢 

```rust
fn setup(mut commands: Commands, windows: Query<&Window, With<PrimaryWindow>>) {
    commands.spawn(Camera2dBundle::default());
    let primary_window = windows.single();
    dbg!("scale_factor: {}", primary_window.scale_factor());
  ```
  
  prints 1 on bevy 0.12 and 2 on bevy 0.11 for Retina.

**Comment by bytemunch** [comment]
Very strange, `winit` 0.28.7 should have fixed this not broken it. 
https://github.com/bevyengine/bevy/pull/9991 was merged because https://github.com/rust-windowing/winit/pull/3118 allegedly fixed things.

Or maybe that's for actual resizing after further digging. Can't see anything in bevy that's changed scaling though?

**Comment by Dimchikkk** [comment]
Created a bug: https://github.com/bevyengine/bevy/issues/10491

**Comment by bytemunch** [comment]
Ah yeah looks like we're getting scale factor before window exists? But should still fire `WindowScaleFactorChanged` event when it updates, which should make this problem disappear on it's own.

**Comment by Dimchikkk** [comment]
> Ah yeah looks like we're getting scale factor before window exists? But should still fire `WindowScaleFactorChanged` event when it updates, which should make this problem disappear on it's own.

Yeah, looks like this, but yeah `WindowScaleFactorChanged` is not fired.

**Comment by Dimchikkk** [comment]
@bytemunch I guess there should be the way to wait until window is created and then read scale factor once...

**Comment by Dimchikkk** [comment]
Okay, the same issue was already reported by someone else... it's marked as the issue to fix for 0.12.1, so hopefully fix will come soonish :)

**Review by Dimchikkk — APPROVED** [review]

**Pull request merged**
