### PR TITLE
Password plugin

### PR DESCRIPTION
**Pull request by bytemunch**
adds password fields back as a feature

also refactors input.rs for more granular system ordering

this version works with multi-byte unicode too, as input and/or password blockers

### CODE REVIEW

**Comment by bytemunch** [comment]
Feature gates were making plugin interoperation very challenging, I removed them in latest commit, not sure how to achieve working interoperability between plugins using `#[cfg(features="whatever")]` without rewriting every function that needs an optional component :/

**Comment by Dimchikkk** [comment]
Looks good!

**Comment by Dimchikkk** [comment]
https://github.com/StaffEngineer/bevy_cosmic_edit/assets/111751109/587ce0f9-f071-46f9-b0db-3ad877110d21


What do you think about moving towards beautifying the text input (adding some animations, etc)? And maybe adding some docs.. so we can do some marketing in bevy channels haha

**Review by Dimchikkk — APPROVED** [review]

**Comment by bytemunch** [comment]
@StaffEngineer Docs definitely, I think animations like that will be tough with the current rendering system, but that should be plugin-ified before long. Moving rendering to shader/GPU might present better opportunity for the flashy stuff

**Pull request merged**
