### PR TITLE
Placeholders

### PR DESCRIPTION
**Pull request by bytemunch**
Got this far, been at war with the borrow checker for a while, beer time

### CODE REVIEW

**Comment by StaffEngineer** [comment]
@bytemunch a bit buggy on removing last char from main editor.... great start anyway 🍻

**Comment by Dimchikkk** [comment]
@bytemunch great start 🍻 I made few improvements 🙊

**Comment by Dimchikkk** [comment]
@bytemunch is it ready to be merged? :)

**Comment by bytemunch** [comment]
It feels like it, I was sure there was more to do yesterday, maybe I just got a bit stressed at it and it was just color and cursor. I'll do a wasm test then make it ready if all goes well

**Pull request merged**
