### PR TITLE
fix wasm breaking when using plugin defaults

### PR DESCRIPTION
**Pull request by bytemunch**
noticed wasm breaking when not supplying a font as bytes.

may be a better way to fix than bundling a font, bit unsure.

### CODE REVIEW

**Comment by Dimchikkk** [comment]
Yeah, ideally user wants to make a request on wasm, download font form some web location and supply it to the plugin. Bundling font into wasm binary increases binary significantly. But this is reasonable default, improvement 👍

**Comment by Dimchikkk** [comment]
@bytemunch oh, this will increase size of plugin :/

(it is 158 kB as for now, so it will make the size +197 KB = 355 KB roughly)

**Comment by Dimchikkk** [comment]
maybe it's better to take the font bevy includes as default font :) it's smaller than 197KB

**Comment by bytemunch** [comment]
yeah i think i'll pop it in a new issue and try get to it tomorrow, size is so important on the web

**Pull request merged**
