### PR TITLE
Update to bevy 0.15

### PR DESCRIPTION
**Pull request by ActuallyHappening**
These should update to bevy 0.15

### CODE REVIEW

**Comment by ActuallyHappening** [comment]
Now I'm going to work on porting the semantics to using required components

**Comment by ActuallyHappening** [comment]
Hey @Dimchikkk I would like a place to discuss some design changes I think would benefit this project for my own use cases, but there is no thread on the bevy discord and your discord account isn't accepting messages from non-friends
Can you enable the github discussions board? Or, actually, I'll write in the issue

**Comment by ActuallyHappening** [comment]
OK, at this point there are only a few outstanding points to me:
- No 3D support
- This random bug with ui rendering where it starts squished
When bevy_editor_pls gets updated to bevy 0.15 I'll be able to quickly fix the squished ui bug, the 3D support I'll seperate into a different PR because I don't want that to hold back merging bevy 0.15 support

Please give me feedback if the direction the API has gone in all of my major changes is OK! The only type I'm still not sure about is `CosmicEditor`:
- Is the `CosmicEditor` component an optional extra? Only for focussed `CosmicEditBuffer`s? IDK and I think I would understand this project better if I did know

**Comment by Dimchikkk** [comment]
> When bevy_editor_pls gets updated to bevy 0.15 I'll be able to quickly fix the squished ui bug

could you elaborate pls? I don't see how bevy_editor_pls is related to the bug :)

**Comment by ActuallyHappening** [comment]
> > When bevy_editor_pls gets updated to bevy 0.15 I'll be able to quickly fix the squished ui bug
> 
> could you elaborate pls? I don't see how bevy_editor_pls is related to the bug :)

I meant, I don't know what is causing the bug atm but will likely be able to debug it with `bevy_editor_pls`. I suspect there is some flag in one of the existing components like `CosmicEditor.cursor_visible` that has some weird interaction with bounds checking, but I'm not sure what is causing it currently

**Comment by ActuallyHappening** [comment]
OK @Dimchikkk I've fixed the final UI bug
I have quite a few more improvements, esspecially 3D, that I'll prepare in a seperate PR for. Currently, I have two patch.crates-io entries for dev-dependencies that are just early access to bevy 0.15 supporting libraries (for bevy_editor_pls and transform-gizmo). bevy_editor_pls helped me find the bug (no correctly handling the redraw flag on cosmic_text::Buffer/Editor)

All in all, this can be published

**Comment by Dimchikkk** [comment]
Thank you for your work 👍

**Comment by Dimchikkk** [comment]
> error: failed to prepare local package for uploading
> 
> Caused by:
>   failed to select a version for the requirement `bevy_editor_pls = "^0.11.0"`
>   candidate versions found which didn't match: 0.10.0, 0.9.0, 0.8.1, ...
>   location searched: crates.io index
>   required by package `bevy_cosmic_edit v0.26.0`

Failed during publishing :/

**Comment by Dimchikkk** [comment]
Can we remove TODO.md and bevy_editor_pls from dev deps?

**Comment by ActuallyHappening** [comment]
Oh yeah, though its already merged
I had those in for testing purposes

**Comment by Dimchikkk** [comment]
If you can open new PR pls

**Pull request merged**
