### PR TITLE
Enable cursor blinking

### LINKED ISSUE #13: Cursor blinking
Enable cursor blinking, something like that should work:

image (9)

### PR DESCRIPTION
**Pull request by Dimchikkk**
Fixes https://github.com/StaffEngineer/bevy_cosmic_edit/issues/13

### CODE REVIEW

**Comment by bytemunch** [comment]
I like it, I'm gonna add some logic to only show cursor on active editor. Not sure what to do about alpha backgrounds for editors tho, cursor doesn't seem to pick up the transparency when disappearing

**Comment by Dimchikkk** [comment]
>  cursor doesn't seem to pick up the transparency when disappearing

Maybe you can modify some example to have such setup, it seems I can't reproduce the bug. 

Edit: we can fix it as follow up :)

**Comment by bytemunch** [comment]
yeah seems like a separate issue, I noticed it in multiple_sprites, the second widget has a shadow of the cursor when blinking

**Comment by Dimchikkk** [comment]
Ah, I see it now, thx :)

**Pull request merged**
